### ISSUE TITLE
will there be any active contributions for this package going forward ? last commit was 3 years ago.

### ISSUE THREAD

**Issue by learner35** [svetlyak40wt/django-globals#29]
will there be any active contributions for this package going forward ? last commit was 3 years ago.

**Comment by therefromhere** [comment]
Hi, yes I'm able to update. Is there a specific issue other than Django compatibility version bumps?

**Comment by learner35** [comment]
Thanks John! We are planning to use the package just checking if there will
be active contributions for this project  in future.. if any issues, will
report back..

Thanks,
Chandra Neeli
